services:
  postgres:
    image: postgis/postgis:16-master
    container_name: mozio-project-postgres
    ports:
      - 5433:5432
    networks:
      - mozio-project-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mozio_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: mozio-project-redis
    ports:
      - 6379:6379
    networks:
      - mozio-project-network

networks:
  mozio-project-network:
    driver: bridge
